routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainPageController@index');


Route::resource('/update_size', 'UpdateSizeChartController');
Route::resource('/update_main-image', 'UpdateMainImageController');
Route::resource('/update_backimage', 'UpdateBackImageController');
Route::resource('/update_pc_main-image', 'UpdatePColorImageController');

Route::resource('/tracking', 'TrackingController');

Route::resource('/newtracking', 'TrackingNewController');


Route::resource('orderhistory', 'HistoryController');
Route::get('/trackinghistory/{id}', 'HistoryController@showtracking');

Route::resource('admin-orderhistory', 'AdminHistoryController');


Route::resource('shop', 'CatalogController');
Route::get('/men', 'CatalogController@index');
Route::get('/women', 'CatalogController@women');



Route::resource('shopping_catalog', 'ShoppingCatalog_Controller');

Route::resource('main', 'MainPageController');

Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'ShoppingCatalog_Controller@myformAjax'));

//Route::post('/search', 'ShoppingCatalog_Controller@searchbox');
Route::get('/searchfilter', 'ShoppingCatalog_Controller@searchbox');









Route::get('/ayam', function () {
    return view('layouts.mango.checkout');
});


//angular route

Route::get('/newcheckout' , function(){
  return view('newcheckout.index');
});


// Route::get('/material', function () {
//     return view('material.create');
// });

Route::get('/checkout-shipping', function () {
    return view('checkout.shipping');
});

Route::get('/checkout-delivery', function () {
    return view('checkout.delivery');
});

Route::get('/checkout-payment', function () {
    return view('checkout.payment');
});

Route::get('/checkout-invoice', function () {
    return view('checkout.invoice');
});




Auth::routes();

Route::get('/print', function(){
    return view('admin_history.show');
});

Route::get('/orderadmin' , 'OrderRecordController@index');

Route::get('/printorder/{id}' , 'AdminHistoryController@downloadPDF');
Route::post('/printorder/{id}' , 'AdminHistoryController@downloadPDF');


Route::get('/admin_home', 'AdminHomeController@index');

//Route::get('/cart','CartController@index');
//Route::get('/cart/addItem/{id}','CartController@addItem');

Route::get('/addProduct/{id}', 'CartController@addItem');
Route::post('/addProduct', 'CartController@addItem');

Route::get('/removeItem/{id}', 'CartController@removeItem');

Route::get('/updateItem', 'CartController@updateItem');

Route::post('/updateItem', 'CartController@updateItem');

Route::get('/cart', 'CartController@showCart');

Route::get('/saveDetail', 'Cart_sizeController@masukLaSetan');

Route::resource('cart_size', 'Cart_sizeController');

Route::post('/simpanCart', 'CartController@store');

Route::get('/destroyItem', 'CartController@destroyItem');

Route::post('/destroyItem', 'CartController@destroyItem');




Route::get('/print', 'InvoiceController@printInvoice');

//Route::get('/product_photo', 'Product_photoController@index');
// Route::post('/product_photo', 'Product_photoController@uploadSubmit');
// Route::resource('/product_photo', 'Product_photoController');
// Route::get('/product_photo/{id}', 'CartController@show');

Route::resource('/product_photo', 'Product_PhotosController');

Route::get('/checkout-invoice', function () {
    return view('checkout.invoice');
});

Route::get('/basket' , 'BasketController@index');
Route::post('/basket' , 'BasketController@index');
Route::post('/hantarla' , 'BasketController@store');


Route::resource('category', 'CategoryController');
Route::resource('brand', 'BrandController');
Route::resource('size_type', 'Size_TypesController');
Route::resource('size_item', 'Size_ItemsController');
Route::resource('material', 'MaterialsController');
Route::resource('product', 'ProductController');

Route::resource('product_price', 'Product_PricesController');


Route::resource('customer', 'CustomerController');

Route::resource('prine', 'PrineController');
Route::resource('margin', 'MarginsController');
Route::resource('currency', 'CurrenciesController');




Route::get('/checkout' , 'CheckoutController@index');
Route::post('/formvalidate' , 'CheckoutController@formvalidate');
Route::get('/thankyou', function(){
  return view ('profile.thankyou');
});

//route for profile



Route::get('/orderdetail' , 'ProfileController@orders');

Route::get('/address' , 'ProfileController@address');
Route::get('/tukarla' , 'ProfileController@changeAddress');
Route::post('/changeAddress' , 'ProfileController@tukarAddress');

Route::get('/password' , 'ProfileController@Password');
Route::post('/tukarpassword' , 'ProfileController@updatePassword');

//end route for profile

Route::resource('shop_men', 'ShopController');
Route::get('/shop_women', 'ShopController@women');
Route::resource('order', 'OrderController');
Route::get('/bayar/{id}' , 'PaymentController@CreatePayment');
Route::post('/bayar/{id}' , 'PaymentController@CreatePayment');
Route::get('/bayarshipping' , 'TrackingPaymentController@CreatePayment');
Route::post('/bayarshipping' , 'TrackingPaymentController@CreatePayment');
Route::get('/paymentresponse','PaymentController@PaymentComplete');
Route::post('/paymentresponse','PaymentController@PaymentComplete');
Route::get('webhook', 'GuzzleController@handleWebhook');
Route::get('/testemail' , 'MailController@SendEmail');

Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'Product_PricesController@myformAjax'));
Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'ProductController@myformAjax'));
Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'Product_PhotosController@myformAjax'));




Route::resource('moq_type', 'Moq_TypesController');
Route::resource('moq_item', 'Moq_ItemsController');

Route::get('/invoice' , 'InvoiceController@createInvoice');



Route::get('/order', function () {
    return view('order.index');
});

Route::group(['middleware' => 'auth'], function()
{
  
  Route::get('/welcome', function()
  {
       return view('welcome');
       
  })->name('welcome');

  
  
  Route::get('/wholesalerhome', function()
  {
       return view('wholesalerhome');

  })->name('wholesalerhome');

  Route::get('/shopping', function()
  {
       return view('shopping');

  })->name('shopping');

  Route::get('/profile', '\App\Http\Controllers\ProfileController@index')->name('profile');


  Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

  //Route::get('/', 'Auth\LoginController@showCat');


});

  Route::get('session/get', 'SessionController@getSession');
  Route::get('session/put', 'SessionController@storeSessionData');
  Route::get('session/forget', 'SessionController@forgetSession');

resources/views/product.bak/create.blade.php
<!DOCTYPE html>
<html>

  @include('layouts.head')

  <body class="fixed-header ">
   

  @include('layouts.sidebar')

     @include('layouts.topbar')

      
      <!-- START PAGE CONTENT WRAPPER -->
      <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content ">
          <!-- START JUMBOTRON -->
          <div class="jumbotron" data-pages="parallax">
            <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
              <div class="inner">
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                  <li>
                    <a href="{{url('/')}}">MudahBorong</a>
                  </li>
                  <li><a href="#" class="active">Insert Product</a>
                  </li>
                </ul>
                <!-- END BREADCRUMB -->
              </div>
            </div>
          </div>
          <!-- END JUMBOTRON -->
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <!-- BEGIN PlACE PAGE CONTENT HERE -->


                 <!--  page header -->
                <div class="col-lg-12">
                    <h1 class="page-header">Insert New Product</h1>
                </div>
                 <!-- end  page header -->
           

             <div class="row">
                <div class="col-lg-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">     

                        </div>

             <div class="container" >

              <form action="/product" method="POST"  enctype="multipart/form-data">
              
              {!! csrf_field() !!}


              <div class="form-group row">
                    <div class="form-group {{ $errors->has('main_image') ? ' has-error' : '' }}">
                      <label class="col-sm-2 control-label">Main Image</label>
                        <div class="col-sm-5">
                          <input type="file" name="main_image" class="form-control">
                          @if ($errors->has('main_image'))
                          <span class="help-block">
                          <strong>{{ $errors->first('main_image') }}</strong>
                          </span>
                          @endif
                        </div>
                    </div>
                    </div>


                    <div class="form-group row">
                    <div class="form-group {{ $errors->has('Back_image') ? ' has-error' : '' }}">
                      <label class="col-sm-2 control-label">Back Image</label>
                        <div class="col-sm-5">
                          <input type="file" name="back_image" class="form-control">
                          @if ($errors->has('back_image'))
                          <span class="help-block">
                          <strong>{{ $errors->first('back_image') }}</strong>
                          </span>
                          @endif
                        </div>
                    </div>
                    </div>


              <div class="form-group row">
              <div class="form-group {{ $errors->has('p_name') ? ' has-error' : '' }}">
              <label class="col-sm-2 control-label">Product Name</label>
              <div class="col-sm-5">
              <input type="text" name="p_name" class="form-control" required>
              @if ($errors->has('p_name'))
                  <span class="help-block">
                      <strong>{{ $errors->first('p_name') }}</strong>
                  </span>
              @endif
            </div>
            </div>
            </div>


            <div class="form-group row">
              <div class="form-group {{ $errors->has('release_date') ? ' has-error' : '' }}">
              <label class="col-sm-2 control-label">Release Date</label>
              <div class="col-sm-2">
              <input type="date" name="release_date" class="form-control">
              @if ($errors->has('release_date'))
                  <span class="help-block">
                      <strong>{{ $errors->first('release_date') }}</strong>
                  </span>
              @endif
            </div>
            </div>
            </div> 

             <div class="form-group row">
             <div class="form-group {{ $errors->has('brand_id') ? ' has-error' : '' }}">
             <label class="col-sm-2 control-label">Brand Name</label>
             <div class="col-sm-5">
             <div class="dropdown">
             <select id="brand_id" name="brand_id" class="form-control" required>
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="">Choose Brand</option>
                @foreach($brand as $post2)
                <option value="{{$post2['id']}}">{{$post2['brand_name']}}</option>
                @endforeach    
              </ul>
            </select>
            </div>
             @if ($errors->has('brand_id'))
                  <span class="help-block">
                      <strong>{{ $errors->first('brand_id') }}</strong>
                  </span>
              @endif
            </div>
            </div>
            </div>


              <script type="text/javascript">
             $(document).ready(function() {
             $('select[name="gender_id"]').on('change', function() {
            var typeID = $(this).val();
            if( typeID) {
                $.ajax({
                    url: '/myform/ajax/'+ typeID,
                    type: "GET",
                    dataType: "json",
                    success:function(data) {

                        
                        $('select[name="category_id"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="category_id"]').append('<option value="'+ key +'">'+ value +'</option>');
                        });

                       }
                   });
                 }else{
                $('select[name="category_id"]').empty();
                  }
                });
                });
              </script>


            <div class="form-group row">
             <div class="form-group {{ $errors->has('gender_id') ? ' has-error' : '' }}">
             <label class="col-sm-2 control-label">Gender</label>
             <div class="col-sm-5">
             <div class="dropdown">
             <select id="gender_id" name="gender_id" class="form-control" required>
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="">Choose Gender</option>
                 @foreach ($gen as $key => $value)
                        <option value="{{ $key }}" >{{ $value }}</option>
                    @endforeach
              </ul>
            </select>
            </div>
             @if ($errors->has('gender_id'))
                  <span class="help-block">
                      <strong>{{ $errors->first('gender_id') }}</strong>
                  </span>
              @endif
            </div>
            </div>
            </div>



            <div class="form-group row">
               <div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
               <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Category</label>
               <div class="col-sm-5">
               <div class="dropdown">
               <select id="category_id" name="category_id" class="form-control" required>
               <span class="caret"></span>
               <ul class="dropdown-menu">
                <option value="">Choose Category</option>
                <div class="dropdown-divider"></div>
               
              </ul>
              </select>
              @if ($errors->has('category_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </span>
                @endif
              </div>
              </div>
              </div>
              </div>

            


            <div class="form-group row">
             <div class="form-group {{ $errors->has('mat_id') ? ' has-error' : '' }}">
             <label class="col-sm-2 control-label">Material Name</label>
             <div class="col-sm-5">
             <div class="dropdown">
             <select id="mat_id" name="mat_id" class="form-control" required>
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="">Choose Material</option>
                @foreach($mat as $post5)
                <option value="{{$post5['id']}}">{{$post5['material_name']}}</option>
                @endforeach 
              </ul>
            </select>
            </div>
             @if ($errors->has('mat_id'))
                  <span class="help-block">
                      <strong>{{ $errors->first('mat_id') }}</strong>
                  </span>
              @endif
            </div>
            </div>
            </div>

            <div class="form-group row">
            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
            <label class="col-sm-2 control-label">Description</label>
            <div class="col-sm-5">
              <textarea class="form-control" name="description" rows="8" cols="40"></textarea>
              @if ($errors->has('description'))
                  <span class="help-block">
                      <strong>{{ $errors->first('description') }}</strong>
                  </span>
              @endif
            </div>
          </div>
          </div>


      <center><input type="submit" name="submit" value = "Create Product"  class="btn btn-primary"></center>
      </form>

    <div class="panel-heading"> </div>

  </div>
  </div>
  </div>
  </div>
            <!-- END PLACE PAGE CONTENT HERE -->
          </div>
          <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->

       @include('layouts.footer')

      @include('layouts.leftsidebar')
      @include('layouts.scripts')

  </body>
</html>

resources/views/product.bak/edit.blade.php
<!DOCTYPE html>
<html>

  @include('layouts.head')

  <body class="fixed-header ">
   

  @include('layouts.sidebar')

     @include('layouts.topbar')

      
      <!-- START PAGE CONTENT WRAPPER -->
      <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content ">
          <!-- START JUMBOTRON -->
          <div class="jumbotron" data-pages="parallax">
            <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
              <div class="inner">
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                  <li>
                    <a href="{{url('/')}}">MudahBorong</a>
                  </li>
                  <li><a href="#" class="active">Edit Product</a>
                  </li>
                </ul>
                <!-- END BREADCRUMB -->
              </div>
            </div>
          </div>
          <!-- END JUMBOTRON -->
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <!-- BEGIN PlACE PAGE CONTENT HERE -->


           <div class="col-lg-12">
                    <h1 class="page-header">Edit Product</h1>
                </div>
                 <!-- end  page header -->
           

             <div class="row">
                <div class="col-lg-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">     

                        </div>

             <div class="container" >

    <form method="post" action="{{action('ProductController@update', $id)}}">

     {{ method_field('PUT') }}
     {!! csrf_field() !!}

     <div class="form-group row">
                    
                      <label class="col-sm-2 control-label"></label>
                        <div class="col-sm-5">
                         <img src="{{ asset('images/main_product/'.$product->main_image) }}" alt="{{$product->brand_image}}" class="img-responsive"/> 
                        </div>
                  
                    </div>
     

      <div class="form-group row">

       <div class="form-group {{ $errors->has('p_name') ? ' has-error' : '' }}">

        <label for="lgFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg">Product Name</label>
        <div class="col-sm-5">
          <input type="text" class="form-control form-control-lg" id="lgFormGroupInput" placeholder="p_name" name="p_name" value="{{$product->p_name}}">
          @if ($errors->has('p_name'))
                  <span class="help-block">
                      <strong>{{ $errors->first('p_name') }}</strong>
                  </span>
              @endif
        </div>
      </div>
      </div>

      <div class="form-group row">
       <div class="form-group {{ $errors->has('release_date') ? ' has-error' : '' }}">
        <label for="lgFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg">Release Date</label>
        <div class="col-sm-5">
          <input type="date" class="form-control form-control-lg" id="lgFormGroupInput" placeholder="release_date" name="release_date" value="{{$product->release_date}}">
           @if ($errors->has('release_date'))
                  <span class="help-block">
                      <strong>{{ $errors->first('release_date') }}</strong>
                  </span>
              @endif
        </div>
      </div>
      </div>

      
      <div class="form-group row">
       <div class="form-group {{ $errors->has('brand_id') ? ' has-error' : '' }}">
        <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Brand Name</label>
        <div class="col-sm-5">
          <div class="dropdown">
            <select id="brand_id" name="brand_id" class="form-control">
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="{{$product->brand_id}}">{{$product->product_brand->brand_name}}</option>
                <div class="dropdown-divider"></div>
                @foreach($brand as $post)
                <option value="{{$post['id']}}">{{$post['brand_name']}}</option>
                @endforeach      
              </ul>
            </select>
            @if ($errors->has('brand_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('brand_id') }}</strong>
                    </span>
                @endif
          </div>
        </div>
      </div>
      </div>

       <div class="form-group row">
       <div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
        <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Product Category</label>
        <div class="col-sm-5">
          <div class="dropdown">
            <select id="category_id" name="category_id" class="form-control">
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="{{$product->category_id}}">{{$product->product_category->category_product}}</option>
                <div class="dropdown-divider"></div>
                @foreach($category as $post2)
                <option value="{{$post2['id']}}">{{$post2['category_product']}}</option>
                @endforeach      
              </ul>
            </select>
            @if ($errors->has('category_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </span>
                @endif
          </div>
        </div>
      </div>
      </div>

      <div class="form-group row">
      <div class="form-group {{ $errors->has('gender') ? ' has-error' : '' }}">
        <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Gender</label>
        <div class="col-sm-5">
          <div class="dropdown">
            <select id="brand_id" name="gender" class="form-control">
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="{{$product->gender}}">{{$product->gender}}</option>
                <div class="dropdown-divider"></div>
                <option value="1">Male</option>
                <option value="2">Female</option>
              </ul>
            </select>
            @if ($errors->has('gender'))
                    <span class="help-block">
                        <strong>{{ $errors->first('gender') }}</strong>
                    </span>
                @endif

          </div>
        </div>
      </div>
      </div>


      <div class="form-group row">
       <div class="form-group {{ $errors->has('mat_id') ? ' has-error' : '' }}">
        <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Material Name</label>
        <div class="col-sm-5">
          <div class="dropdown">
            <select id="mat_id" name="mat_id" class="form-control">
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <option value="{{$product->mat_id}}">{{$product->product_mat->material_name}}</option>
                <div class="dropdown-divider"></div>
                @foreach($mat as $post4)
                <option value="{{$post4['id']}}">{{$post4['material_name']}}</option>
                @endforeach      
              </ul>
            </select>
            @if ($errors->has('mat_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mat_id') }}</strong>
                    </span>
                @endif
          </div>
        </div>
      </div>
      </div>



      <div class="form-group row">
      <div class="form-group {{ $errors->has('escription') ? ' has-error' : '' }}">
        <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Description</label>
        <div class="col-sm-5">
          <textarea name="description" rows="8" cols="80">{{$product->description}}</textarea>
          @if ($errors->has('description'))
                    <span class="help-block">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
                @endif
        </div>
      </div>
      </div>


      <div class="form-group row">
        <div class="col-md-2"></div>
        <button type="submit" class="btn btn-primary" >Update</button>
        <a href="javascript:history.back()" class="btn btn-primary">Back</a>
      </div>
    </form>
  </div>
  </div>
  </div>
  </div>


         <!-- END PLACE PAGE CONTENT HERE -->
          </div>
          <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->

       @include('layouts.footer')

      @include('layouts.leftsidebar')
      @include('layouts.scripts')

  </body>
</html>

resources/views/product.bak/index.blade.php
<!DOCTYPE html>
<html>

  @include('layouts.head')

  <body class="fixed-header ">
   

  @include('layouts.sidebar')

     @include('layouts.topbar')

      
      <!-- START PAGE CONTENT WRAPPER -->
      <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content ">
          <!-- START JUMBOTRON -->
          <div class="jumbotron" data-pages="parallax">
            <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
              <div class="inner">
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                  <li>
                    <a href="{{url('/')}}">MudahBorong</a>
                  </li>
                  <li><a href="#" class="active">Product</a>
                  </li>
                </ul>
                <!-- END BREADCRUMB -->
              </div>
            </div>
          </div>
          <!-- END JUMBOTRON -->



          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <!-- BEGIN PlACE PAGE CONTENT HERE -->

            <link href="{{asset('dist/css/bootstrap.min.css')}}" rel="stylesheet">
            
           <!--  page header -->
                <div class="col-lg-12">
                    <h1 class="page-header">List Of Product</h1>
                </div>
                 <!-- end  page header -->
           

             <div class="row">
                <div class="col-lg-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">     

                        </div>


  <div class="container">
    <table class="table table-striped">
      <thead>


      <tr>

        <td colspan="12" align="right">
          <a  href="{{route('product.create')}}" class="btn btn-primary" >Add New Product
          </a>
        </td>
      </tr>
      <tr>
        <th>Bil</th>
        <th>Image</th>
        <th>Name</th>
        <th>Release Date</th>
        <th>Brand</th>
        <th>Category</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>

        
      </tr>
      </thead>
      <tbody>

      <?php $i = 0 ?>
      @foreach($product as $post)
      <?php $i++ ?>
       <tr>

            <td>{{ $i}}</td>
            <td>
            <img src="{{ 'images/main_product/'.$post['main_image'] }}" alt="{{ $post['main_image'] }}" height="80px"/>
            </td>
            <td>{{$post['p_name']}}  </td>
            <td>{{$post['release_date']}}</td>
            <td>{{ $post->product_brand->brand_name}} </td>  
            <td>{{ $post->product_category->category_product}}</td>
           
  
            <td><a href="{{action('ProductController@show', $post['id'])}}" class="btn btn-info">View <span class="glyphicon glyphicon-eye-open"></span></a></td>
            

            <td><a href="{{action('ProductController@edit', $post['id'])}}" class="btn btn-warning">Edit <span class="glyphicon glyphicon-pencil"></span></a></td>

            <td>
                <form action="{{action('ProductController@destroy', $post['id'])}}" method="post">
                {{csrf_field()}}
                <input name="_method" type="hidden" value="DELETE">
                <button class="btn btn-danger" type="submit">Delete <span class="glyphicon glyphicon-trash"></span></button>
              </form>
            </td>
          </tr>
            @endforeach



      </tbody>
    </table>

    {{$product->links() }}

  </div>
  </div>
  </div>
  </div>
         
             
            <!-- END PLACE PAGE CONTENT HERE -->
          </div>
          <!-- END CONTAINER FLUID -->
        </div>
        <!-- END PAGE CONTENT -->

       @include('layouts.footer')

      @include('layouts.leftsidebar')
      @include('layouts.scripts')

  </body>
</html>